### ISSUE TITLE
Gihub.io issue with weather

### ISSUE THREAD

**Issue by anyakeller** [AlanLeverenz/Vacay#18]
The weather thingie doesn't work on github.io on master.
<img width="670" alt="Screen Shot 2019-09-07 at 2 40 38 PM" src="https://user-images.githubusercontent.com/10265250/64478907-8c82a480-d17d-11e9-8547-64b9109f8805.png">

**Comment by AlanLeverenz** [comment]
weather.js is working in the countries branch. we'll merge it into the master tonight.
